### ISSUE TITLE
Deduplication also removes data < ngram_size

### ISSUE THREAD

**Issue by cceyda** [bigcode-project/bigcode-dataset#35]
I noticed `ngrams` [function](https://github.com/bigcode-project/bigcode-dataset/blob/main/near_deduplication/minhash_deduplication.py#L46) returns empty list when number of tokens is smaller than ngram_size value.
This has the side effect of clustering all sentences with number of tokens smaller than the ngram_size value together & removing them as dupes. Not sure if this is intentional? 
so for the default of ngram_size=5 "a sentence like this" gets removed by default.

Could maybe filter & rerun the deduping with a smaller n_gram value for those sentences.

**Comment by lvwerra** [comment]
cc @ChenghaoMou

**Comment by ChenghaoMou** [comment]
Thanks for pointing this out. Previously in v1, the deduplication uses unigram and keeps all short docs (<10 tokens), but in the dataset created for SantaCoder (post v1.1) and v1.2 candidate use this n-gram code copied from nltk, and increased the n-gram size to 5. This length filtering wasn't intentional at the beginning, though we did want more aggressive deduplication. Later experiments showed better FP and FN rates in Java, JS, and Python, so these settings have been carried over as default in the code.

I will update the README and code to clearly state this detail, and to allow different settings for this as well.

If you have a strong use-case where it shouldn't be applied, or it should be applied with less strict values, please let me know.

**Comment by ChenghaoMou** [comment]
Closing this for now, the update is merged. Feel free to reopen it if there are any issues.
